# -*- coding: utf-8 -*-
from typing import Literal

ExportFormat = Literal["csv", "xlsx", "pdf"]
ExportSection = Literal[
    "transactions",
    "category_summary",
]

CSV_EXPORT_COLUMNS = [
    "expense_id",
    "scope",
    "title",
    "expense_date",
    "created_at",
    "currency",
    "category_id",
    "category_name",
    "group_id",
    "group_name",
    "total_amount",
    "user_amount",
    "recurring_expense_id",
    "recurring_occurrence_date",
]

EXPORT_ALL_SECTIONS: tuple[ExportSection, ...] = (
    "transactions",
    "category_summary",
)

EXPORT_ALLOWED_SECTIONS: dict[ExportFormat, tuple[ExportSection, ...]] = {
    "csv": EXPORT_ALL_SECTIONS,
    "xlsx": EXPORT_ALL_SECTIONS,
    "pdf": EXPORT_ALL_SECTIONS,
}

EXPORT_DEFAULT_SECTIONS: dict[ExportFormat, tuple[ExportSection, ...]] = {
    "csv": EXPORT_ALL_SECTIONS,
    "xlsx": EXPORT_ALL_SECTIONS,
    "pdf": EXPORT_ALL_SECTIONS,
}

EXPORT_LOCALIZATION = {
    "en": {
        "sheet_title": "Summary",
        "document_title": "Expense Summary",
        "generated_at": "Generated at",
        "filename_prefix": "expenses-summary",
        "columns": [
            "Date",
            "Title",
            "Type",
            "Category",
            "Group",
            "Currency",
            "Total amount",
            "Your amount",
        ],
        "scope": {
            "personal": "Personal",
            "group": "Group",
        },
        "empty_group": "N/A",
        "kpi_summary": "Summary",
        "metric": "Metric",
        "value": "Value",
        "total_transactions": "Total transactions",
        "category_breakdown": "Category Breakdown",
        "category": "Category",
        "amount": "Amount",
        "categories": {
            "groceries": "Groceries",
            "restaurants": "Restaurants",
            "coffee_snacks": "Coffee & Snacks",
            "food_delivery": "Food Delivery",
            "food_other": "Food Other",
            "public_transport": "Public Transport",
            "fuel": "Fuel",
            "taxi_rideshare": "Taxi & Rideshare",
            "parking_tolls": "Parking & Tolls",
            "vehicle_maintenance": "Vehicle Maintenance",
            "transport_other": "Transport Other",
            "rent_mortgage": "Rent & Mortgage",
            "household_supplies": "Household Supplies",
            "home_repairs": "Home Repairs",
            "home_other": "Home Other",
            "utilities": "Utilities",
            "internet_phone": "Internet & Phone",
            "subscriptions": "Subscriptions",
            "insurance": "Insurance",
            "bills_other": "Bills Other",
            "medical": "Medical",
            "pharmacy": "Pharmacy",
            "fitness": "Fitness",
            "health_other": "Health Other",
            "entertainment": "Entertainment",
            "clothing": "Clothing",
            "travel": "Travel",
            "gifts": "Gifts",
            "personal_care": "Personal Care",
            "lifestyle_other": "Lifestyle Other",
            "bank_fees": "Bank Fees",
            "savings": "Savings",
            "investments": "Investments",
            "finance_other": "Finance Other",
            "courses": "Courses",
            "books": "Books",
            "education_other": "Education Other",
            "kids_family": "Kids & Family",
            "pets": "Pets",
            "family_other": "Family Other",
            "other": "Other",
        },
    },
    "pl": {
        "sheet_title": "Podsumowanie",
        "document_title": "Podsumowanie wydatkow",
        "generated_at": "Wygenerowano",
        "filename_prefix": "podsumowanie-wydatkow",
        "columns": [
            "Data",
            "Tytul",
            "Zakres",
            "Kategoria",
            "Grupa",
            "Waluta",
            "Kwota calkowita",
            "Twoja kwota",
        ],
        "scope": {
            "personal": "Osobiste",
            "group": "Grupowe",
        },
        "empty_group": "Brak",
        "kpi_summary": "Podsumowanie",
        "metric": "Metryka",
        "value": "Wartosc",
        "total_transactions": "Liczba transakcji",
        "category_breakdown": "Podzial wedlug kategorii",
        "category": "Kategoria",
        "amount": "Kwota",
        "categories": {
            "groceries": "Zakupy spożywcze",
            "restaurants": "Restauracje",
            "coffee_snacks": "Kawa i przekąski",
            "food_delivery": "Dostawa jedzenia",
            "food_other": "Inne jedzenie",
            "public_transport": "Transport publiczny",
            "fuel": "Paliwo",
            "taxi_rideshare": "Taxi i carsharing",
            "parking_tolls": "Parking i opłaty drogowe",
            "vehicle_maintenance": "Konserwacja pojazdu",
            "transport_other": "Inny transport",
            "rent_mortgage": "Czynsz i kredyt",
            "household_supplies": "Artykuły gospodarstwa domowego",
            "home_repairs": "Naprawy domowe",
            "home_other": "Inne domowe",
            "utilities": "Media",
            "internet_phone": "Internet i telefon",
            "subscriptions": "Subskrypcje",
            "insurance": "Ubezpieczenia",
            "bills_other": "Inne rachunki",
            "medical": "Medyczne",
            "pharmacy": "Apteka",
            "fitness": "Fitness",
            "health_other": "Inne zdrowie",
            "entertainment": "Rozrywka",
            "clothing": "Odzież",
            "travel": "Podróże",
            "gifts": "Prezenty",
            "personal_care": "Pielęgnacja osobista",
            "lifestyle_other": "Inny styl życia",
            "bank_fees": "Opłaty bankowe",
            "savings": "Oszczędności",
            "investments": "Inwestycje",
            "finance_other": "Inne finanse",
            "courses": "Kursy",
            "books": "Książki",
            "education_other": "Inna edukacja",
            "kids_family": "Dzieci i rodzina",
            "pets": "Zwierzęta",
            "family_other": "Inna rodzina",
            "other": "Inne",
        },
    },
}
