import {
  Baby,
  Bus,
  Car,
  Coffee,
  Dumbbell,
  Film,
  Fuel,
  Gift,
  GraduationCap,
  Hammer,
  Home,
  Landmark,
  PawPrint,
  Pill,
  PiggyBank,
  Plane,
  Receipt,
  Shield,
  Shirt,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Stethoscope,
  Tag,
  Tv,
  Utensils,
  Wrench,
  Zap,
  CircleQuestionMark,
  BookOpenText
} from "lucide-react";

export const categoryIcons = {
  groceries: ShoppingBag,
  restaurants: Utensils,
  coffee_snacks: Coffee,
  food_delivery: Receipt,

  public_transport: Bus,
  fuel: Fuel,
  taxi_rideshare: Car,
  parking_tolls: Receipt,
  vehicle_maintenance: Wrench,

  rent_mortgage: Home,
  household_supplies: Home,
  home_repairs: Hammer,

  utilities: Zap,
  internet_phone: Smartphone,
  subscriptions: Tv,
  insurance: Shield,

  medical: Stethoscope,
  pharmacy: Pill,
  fitness: Dumbbell,

  entertainment: Film,
  clothing: Shirt,
  travel: Plane,
  gifts: Gift,
  personal_care: Sparkles,

  bank_fees: Landmark,
  savings: PiggyBank,
  investments: Landmark,
  courses: GraduationCap,
  books: BookOpenText,
  savings_investments: PiggyBank,
  courses_books: GraduationCap,
  kids_family: Baby,
  pets: PawPrint,

  food: Utensils,
  transport: Car,
  home: Home,
  bills: Receipt,
  lifestyle: ShoppingBag,
  health: Stethoscope,
  finance: Landmark,
  education: GraduationCap,
  family: Baby,
  custom: Tag,
  other: CircleQuestionMark,
} as const;
