"""init

Revision ID: 31f66dd04db0
Revises: 
Create Date: 2026-04-18 00:20:16.765067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31f66dd04db0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='system_user_roles'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('budget_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('currency', sa.Enum('AED', 'AUD', 'CAD', 'CHF', 'CNY', 'CZK', 'DKK', 'PLN', 'EUR', 'GBP', 'HKD', 'HUF', 'ILS', 'JPY', 'NOK', 'NZD', 'RON', 'SEK', 'SGD', 'TRY', 'USD', 'ZAR', name='currency_enum'), nullable=False),
    sa.Column('period_type', sa.Enum('WEEKLY', 'MONTHLY', name='budget_period_type'), nullable=False),
    sa.Column('allocation_strategy', sa.Enum('FIXED', 'PERCENT_INCOME', 'ZERO_BASED', name='budget_allocation_strategy'), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('income_target', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('include_group_expenses', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='budget_status'), nullable=False),
    sa.Column('template_key', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('period_end >= period_start', name='check_budget_plan_period'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_budget_plans_user_period', 'budget_plans', ['user_id', 'period_start', 'period_end'], unique=False)
    op.create_index('idx_budget_plans_user_status', 'budget_plans', ['user_id', 'status'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'contact_id', name='uq_contact_pair')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='group_status'), nullable=False),
    sa.Column('currency', sa.Enum('AED', 'AUD', 'CAD', 'CHF', 'CNY', 'CZK', 'DKK', 'PLN', 'EUR', 'GBP', 'HKD', 'HUF', 'ILS', 'JPY', 'NOK', 'NZD', 'RON', 'SEK', 'SGD', 'TRY', 'USD', 'ZAR', name='currency_enum'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_user_group_active_name', 'groups', ['created_by', 'name'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_table('income_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('AED', 'AUD', 'CAD', 'CHF', 'CNY', 'CZK', 'DKK', 'PLN', 'EUR', 'GBP', 'HKD', 'HUF', 'ILS', 'JPY', 'NOK', 'NZD', 'RON', 'SEK', 'SGD', 'TRY', 'USD', 'ZAR', name='currency_enum'), nullable=False),
    sa.Column('income_date', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('amount > 0', name='check_income_entry_amount_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_income_entries_user_date', 'income_entries', ['user_id', 'income_date'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('INVITATION', 'BUDGET_NEAR_LIMIT', 'BUDGET_OVERSPENDING', 'UPCOMING_RECURRING_EXPENSE', name='notification_type'), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'URGENT', name='notification_severity'), nullable=True),
    sa.Column('action_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_table('budget_period_summaries',
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('total_income', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_expenses', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_savings', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remaining_budget', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('overspend_flag', sa.Boolean(), nullable=False),
    sa.Column('last_recalculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budget_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('budget_id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('section', sa.Enum('FOOD', 'TRANSPORT', 'HOME', 'BILLS', 'LIFESTYLE', 'HEALTH', 'FINANCE', 'EDUCATION', 'FAMILY', 'OTHER', name='category_section'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_categories_parent_id', 'categories', ['parent_id'], unique=False)
    op.create_index('uq_global_category', 'categories', ['name'], unique=True, postgresql_where=sa.text('user_id IS NULL AND group_id IS NULL'))
    op.create_index('uq_group_category', 'categories', ['group_id', 'name'], unique=True, postgresql_where=sa.text('group_id IS NOT NULL'))
    op.create_index('uq_user_category', 'categories', ['user_id', 'name'], unique=True, postgresql_where=sa.text('user_id IS NOT NULL'))
    op.create_table('group_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MEMBER', name='group_member_role'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'LEFT', name='group_member_status'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'group_id', name='uq_group_member')
    )
    op.create_table('invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('CONTACT', 'GROUP', name='invitation_type'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED', 'ARCHIVED', name='invitation_status'), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(CAST(type AS TEXT) = 'GROUP' AND group_id IS NOT NULL) OR (CAST(type AS TEXT) = 'CONTACT' AND group_id IS NULL)", name='ck_invitation_type_group_logic'),
    sa.CheckConstraint('from_user_id <> to_user_id', name='ck_no_self_invite'),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'from_user_id', 'to_user_id', 'group_id', name='uq_unique_invitation')
    )
    op.create_index(op.f('ix_invitations_id'), 'invitations', ['id'], unique=False)
    op.create_table('settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=True),
    sa.Column('to_user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('currency', sa.Enum('AED', 'AUD', 'CAD', 'CHF', 'CNY', 'CZK', 'DKK', 'PLN', 'EUR', 'GBP', 'HKD', 'HUF', 'ILS', 'JPY', 'NOK', 'NZD', 'RON', 'SEK', 'SGD', 'TRY', 'USD', 'ZAR', name='currency_enum'), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'PAYPAL', 'OFFSET_APPLIED', 'OFFSET_FORGIVEN', name='payment_method'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PENDING_PAYPAL', 'COMPLETED', 'FAILED', name='settlement_status'), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('paypal_order_id', sa.String(length=255), nullable=True),
    sa.Column('paypal_capture_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('from_user_id != to_user_id', name='check_no_self_settlement'),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_settlements_from_user', 'settlements', ['from_user_id'], unique=False)
    op.create_index('idx_settlements_group', 'settlements', ['group_id'], unique=False)
    op.create_index('idx_settlements_paypal_order_id', 'settlements', ['paypal_order_id'], unique=False)
    op.create_index('idx_settlements_to_user', 'settlements', ['to_user_id'], unique=False)
    op.create_table('budget_pools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('pool_type', sa.Enum('FIXED_AMOUNT', 'PERCENT_INCOME', name='budget_pool_type'), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('alert_threshold', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('spent_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remaining_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rollover_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rollover_enabled', sa.Boolean(), nullable=False),
    sa.Column('rollover_negative_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_recalculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('alert_threshold > 0 AND alert_threshold <= 100', name='check_budget_pool_alert_threshold_range'),
    sa.CheckConstraint('target_value > 0', name='check_budget_pool_target_positive'),
    sa.ForeignKeyConstraint(['budget_id'], ['budget_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_budget_pools_budget_id', 'budget_pools', ['budget_id'], unique=False)
    op.create_table('recurring_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('AED', 'AUD', 'CAD', 'CHF', 'CNY', 'CZK', 'DKK', 'PLN', 'EUR', 'GBP', 'HKD', 'HUF', 'ILS', 'JPY', 'NOK', 'NZD', 'RON', 'SEK', 'SGD', 'TRY', 'USD', 'ZAR', name='currency_enum'), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('split_type', sa.Enum('EQUAL', 'PERCENT', 'EXACT', name='split_type'), nullable=True),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY', name='recurrence_frequency'), nullable=False),
    sa.Column('interval_count', sa.Integer(), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('next_due_on', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'ENDED', 'ARCHIVED', name='recurring_expense_status'), nullable=False),
    sa.Column('last_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('(day_of_month IS NULL) OR (day_of_month BETWEEN 1 AND 31)', name='check_recurring_day_of_month_range'),
    sa.CheckConstraint('(day_of_week IS NULL) OR (day_of_week BETWEEN 0 AND 6)', name='check_recurring_day_of_week_range'),
    sa.CheckConstraint('(ends_on IS NULL) OR (ends_on >= starts_on)', name='check_recurring_ends_on_after_starts_on'),
    sa.CheckConstraint('(group_id IS NULL AND split_type IS NULL) OR (group_id IS NOT NULL AND split_type IS NOT NULL)', name='check_recurring_split_type_group'),
    sa.CheckConstraint('interval_count > 0', name='check_recurring_interval_positive'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recurring_expenses_group_status', 'recurring_expenses', ['group_id', 'status'], unique=False)
    op.create_index('idx_recurring_expenses_status_next_due_on', 'recurring_expenses', ['status', 'next_due_on'], unique=False)
    op.create_index('idx_recurring_expenses_user_status', 'recurring_expenses', ['user_id', 'status'], unique=False)
    op.create_table('budget_pool_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('spent_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remaining_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('usage_percentage', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_recalculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('ON_TRACK', 'WARNING', 'EXCEEDED')", name='check_budget_pool_states_status'),
    sa.ForeignKeyConstraint(['budget_id'], ['budget_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pool_id'], ['budget_pools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('budget_id', 'pool_id', name='uq_budget_pool_states_budget_pool')
    )
    op.create_table('budget_rollovers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_budget_id', sa.Integer(), nullable=False),
    sa.Column('to_budget_id', sa.Integer(), nullable=False),
    sa.Column('from_pool_id', sa.Integer(), nullable=True),
    sa.Column('to_pool_id', sa.Integer(), nullable=True),
    sa.Column('rollover_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_negative', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['from_budget_id'], ['budget_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_pool_id'], ['budget_pools.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_budget_id'], ['budget_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_pool_id'], ['budget_pools.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('AED', 'AUD', 'CAD', 'CHF', 'CNY', 'CZK', 'DKK', 'PLN', 'EUR', 'GBP', 'HKD', 'HUF', 'ILS', 'JPY', 'NOK', 'NZD', 'RON', 'SEK', 'SGD', 'TRY', 'USD', 'ZAR', name='currency_enum'), nullable=False),
    sa.Column('split_type', sa.Enum('EQUAL', 'PERCENT', 'EXACT', name='split_type'), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('recurring_expense_id', sa.Integer(), nullable=True),
    sa.Column('recurring_occurrence_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expense_date', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('receipt_image_url', sa.Text(), nullable=True),
    sa.Column('receipt_text', sa.Text(), nullable=True),
    sa.CheckConstraint('(group_id IS NULL AND split_type IS NULL) OR (group_id IS NOT NULL AND split_type IS NOT NULL)', name='check_split_type_group'),
    sa.CheckConstraint('(recurring_expense_id IS NULL AND recurring_occurrence_date IS NULL) OR (recurring_expense_id IS NOT NULL AND recurring_occurrence_date IS NOT NULL)', name='check_recurring_expense_occurrence'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recurring_expense_id'], ['recurring_expenses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_expenses_category', 'expenses', ['category_id'], unique=False)
    op.create_index('idx_expenses_expense_date', 'expenses', ['expense_date'], unique=False)
    op.create_index('idx_expenses_group_id', 'expenses', ['group_id'], unique=False)
    op.create_index('idx_expenses_recurring_expense_id', 'expenses', ['recurring_expense_id'], unique=False)
    op.create_index('idx_expenses_recurring_occurrence_date', 'expenses', ['recurring_occurrence_date'], unique=False)
    op.create_index('idx_expenses_user_group_expense_date', 'expenses', ['user_id', 'group_id', 'expense_date'], unique=False)
    op.create_index('idx_expenses_user_id', 'expenses', ['user_id'], unique=False)
    op.create_index('uq_expenses_recurring_occurrence', 'expenses', ['recurring_expense_id', 'recurring_occurrence_date'], unique=True, postgresql_where=sa.text('recurring_expense_id IS NOT NULL'))
    op.create_table('recurring_expense_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recurring_expense_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('share_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('share_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('(share_amount IS NOT NULL AND share_percentage IS NULL) OR (share_amount IS NULL AND share_percentage IS NOT NULL) OR (share_amount IS NULL AND share_percentage IS NULL)', name='check_recurring_participant_share_shape'),
    sa.CheckConstraint('(share_amount IS NULL OR share_amount >= 0)', name='check_recurring_participant_share_amount_non_negative'),
    sa.CheckConstraint('(share_percentage IS NULL OR (share_percentage >= 0 AND share_percentage <= 100))', name='check_recurring_participant_share_percentage_range'),
    sa.ForeignKeyConstraint(['recurring_expense_id'], ['recurring_expenses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recurring_expense_id', 'user_id', name='uq_recurring_expense_participant_user')
    )
    op.create_index('idx_recurring_expense_participants_user_id', 'recurring_expense_participants', ['user_id'], unique=False)
    op.create_table('savings_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('budget_pool_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('auto_allocate_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('auto_allocate_amount IS NULL OR auto_allocate_amount >= 0', name='check_savings_goal_auto_allocate_non_negative'),
    sa.CheckConstraint('current_amount >= 0', name='check_savings_goal_current_non_negative'),
    sa.CheckConstraint('target_amount > 0', name='check_savings_goal_target_positive'),
    sa.ForeignKeyConstraint(['budget_pool_id'], ['budget_pools.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expense_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('share_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('expense_id', 'user_id', name='uq_expense_user')
    )
    op.create_index('idx_expense_shares_user', 'expense_shares', ['user_id'], unique=False)
    op.create_index('idx_expense_shares_user_expense', 'expense_shares', ['user_id', 'expense_id'], unique=False)
    op.create_table('goal_states',
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=True),
    sa.Column('current_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('progress_percentage', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_recalculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'COMPLETED', 'PAUSED')", name='check_goal_states_status'),
    sa.ForeignKeyConstraint(['budget_id'], ['budget_plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['goal_id'], ['savings_goals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('goal_id')
    )
    op.create_table('savings_goal_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=True),
    sa.Column('budget_pool_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('allocation_type', sa.String(length=12), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("allocation_type IN ('manual', 'auto')", name='check_savings_goal_allocation_type'),
    sa.CheckConstraint('amount > 0', name='check_savings_goal_allocation_amount_positive'),
    sa.ForeignKeyConstraint(['budget_id'], ['budget_plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['budget_pool_id'], ['budget_pools.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['goal_id'], ['savings_goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('savings_goal_allocations')
    op.drop_table('goal_states')
    op.drop_index('idx_expense_shares_user_expense', table_name='expense_shares')
    op.drop_index('idx_expense_shares_user', table_name='expense_shares')
    op.drop_table('expense_shares')
    op.drop_table('savings_goals')
    op.drop_index('idx_recurring_expense_participants_user_id', table_name='recurring_expense_participants')
    op.drop_table('recurring_expense_participants')
    op.drop_index('uq_expenses_recurring_occurrence', table_name='expenses', postgresql_where=sa.text('recurring_expense_id IS NOT NULL'))
    op.drop_index('idx_expenses_user_id', table_name='expenses')
    op.drop_index('idx_expenses_user_group_expense_date', table_name='expenses')
    op.drop_index('idx_expenses_recurring_occurrence_date', table_name='expenses')
    op.drop_index('idx_expenses_recurring_expense_id', table_name='expenses')
    op.drop_index('idx_expenses_group_id', table_name='expenses')
    op.drop_index('idx_expenses_expense_date', table_name='expenses')
    op.drop_index('idx_expenses_category', table_name='expenses')
    op.drop_table('expenses')
    op.drop_table('budget_rollovers')
    op.drop_table('budget_pool_states')
    op.drop_index('idx_recurring_expenses_user_status', table_name='recurring_expenses')
    op.drop_index('idx_recurring_expenses_status_next_due_on', table_name='recurring_expenses')
    op.drop_index('idx_recurring_expenses_group_status', table_name='recurring_expenses')
    op.drop_table('recurring_expenses')
    op.drop_index('idx_budget_pools_budget_id', table_name='budget_pools')
    op.drop_table('budget_pools')
    op.drop_index('idx_settlements_to_user', table_name='settlements')
    op.drop_index('idx_settlements_paypal_order_id', table_name='settlements')
    op.drop_index('idx_settlements_group', table_name='settlements')
    op.drop_index('idx_settlements_from_user', table_name='settlements')
    op.drop_table('settlements')
    op.drop_index(op.f('ix_invitations_id'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_table('group_members')
    op.drop_index('uq_user_category', table_name='categories', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.drop_index('uq_group_category', table_name='categories', postgresql_where=sa.text('group_id IS NOT NULL'))
    op.drop_index('uq_global_category', table_name='categories', postgresql_where=sa.text('user_id IS NULL AND group_id IS NULL'))
    op.drop_index('idx_categories_parent_id', table_name='categories')
    op.drop_table('categories')
    op.drop_table('budget_period_summaries')
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_income_entries_user_date', table_name='income_entries')
    op.drop_table('income_entries')
    op.drop_index('uq_user_group_active_name', table_name='groups', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_table('groups')
    op.drop_table('contacts')
    op.drop_index('idx_budget_plans_user_status', table_name='budget_plans')
    op.drop_index('idx_budget_plans_user_period', table_name='budget_plans')
    op.drop_table('budget_plans')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
