"""Add message_key and context to notifications

Revision ID: 6549adfae7c6
Revises: 20260425_042607
Create Date: 2026-05-11 22:22:11.802025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6549adfae7c6'
down_revision: Union[str, Sequence[str], None] = '20260425_042607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('message_key', sa.Text(), nullable=True))
    op.add_column('notifications', sa.Column('context', sa.Text(), nullable=True))
    op.create_index('ix_notifications_user_status', 'notifications', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_user_status', table_name='notifications')
    op.drop_column('notifications', 'context')
    op.drop_column('notifications', 'message_key')
    # ### end Alembic commands ###
