from enum import Enum

class CurrencyEnum(str, Enum):
    AED = "AED"
    AUD = "AUD"
    CAD = "CAD"
    CHF = "CHF"
    CNY = "CNY"
    CZK = "CZK"
    DKK = "DKK"
    PLN = "PLN"
    EUR = "EUR"
    GBP = "GBP"
    HKD = "HKD"
    HUF = "HUF"
    ILS = "ILS"
    JPY = "JPY"
    NOK = "NOK"
    NZD = "NZD"
    RON = "RON"
    SEK = "SEK"
    SGD = "SGD"
    TRY = "TRY"
    USD = "USD"
    ZAR = "ZAR"